# Deploy do Postgre
apiVersion: apps/v1 # Versão da API do Kubernetes que será utilizada na criação do objeto no kubernetes (kubectl api-resources)
kind: Deployment   # Tipo de objeto que será criado
metadata:           # Metadados do objeto (nome, labels, etc)
  name: postgre
spec:               # Todas especificações do objeto
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:         # Estrutura dos pods criados pelo deployment
    metadata:
      labels:
        app: postgre
    spec:
      containers:   # Especificações do container
        - name: postgre
          image: postgres:13.1
          env:
            - name: POSTGRES_PASSWORD
              value: Passw0rd2024!
            - name: POSTGRES_USER
              value: reviewfilmes
            - name: POSTGRES_DB
              value: reviewfilmes
          ports:
            - containerPort: 5432
---
# Service
apiVersion: v1 
kind: Service   
metadata:          
  name: postgre
spec:
  selector:
    app: postgre # Define o serviço que o service irá expor
  ports:
    - port: 5432 # Porta onde o serviço será exposto
---
# Deploy da Aplicação Web
apiVersion: apps/v1 
kind: Deployment   
metadata:           
  name: reviewfilmes
spec:               
  replicas: 1
  selector:
    matchLabels:
      app: reviewfilmes
  template:         
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:   
        - name: reviewfilmes
          image: tmansur/review-filmes:v1
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgre;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rd2024!"
          ports:
            - containerPort: 8080
---
# Service
apiVersion: v1 
kind: Service   
metadata:          
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes 
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort